"""add review

Revision ID: 11e51d574468
Revises: d20014c92d39
Create Date: 2025-02-28 22:43:18.610499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e51d574468'
down_revision = 'd20014c92d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_customers_reviews_item_id_items'), 'items', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customers_reviews_item_id_items'), type_='foreignkey')
        batch_op.drop_column('item_id')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
