"""add review

Revision ID: 61619f9973f6
Revises: 11e51d574468
Create Date: 2025-02-28 22:44:10.567899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61619f9973f6'
down_revision = '11e51d574468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers_reviews', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
