"""add review

Revision ID: 85c8e9f71c4d
Revises: 61619f9973f6
Create Date: 2025-02-28 22:47:54.355524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c8e9f71c4d'
down_revision = '61619f9973f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_customers_reviews_customer_id_customers'), 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customers_reviews_customer_id_customers'), type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
