"""add review

Revision ID: d20014c92d39
Revises: e0803e386111
Create Date: 2025-02-28 22:41:30.968329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20014c92d39'
down_revision = 'e0803e386111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers_reviews')
    # ### end Alembic commands ###
